<a href="https://colab.research.google.com/github/siahw/notes/blob/main/%E2%80%9CAAT0320_0314_livecoding%E2%80%9D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!wget "https://raw.githubusercontent.com/amephraim/nlp/master/texts/J.%20K.%20Rowling%20-%20Harry%20Potter%201%20-%20Sorcerer's%20Stone.txt"

--2022-03-25 09:21:54--  https://raw.githubusercontent.com/amephraim/nlp/master/texts/J.%20K.%20Rowling%20-%20Harry%20Potter%201%20-%20Sorcerer's%20Stone.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 439742 (429K) [text/plain]
Saving to: ‘J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt’

J. K. Rowling - Har 100%[===================>] 429.44K  --.-KB/s    in 0.02s   

2022-03-25 09:21:54 (20.8 MB/s) - ‘J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt’ saved [439742/439742]



In [3]:
with open("J. K. Rowling - Harry Potter 1 - Sorcerer's Stone.txt", 'r') as f:
  strings = f.readlines() 


In [4]:
sample_text= ''.join(strings[:500]).replace('\n', ' ').replace('Mr.', 'Mr').replace('Mrs.', 'Mrs')

In [5]:
sliced_text = sample_text.split('. ') #sliced by sentence

In [6]:
# slice by word
sliced_text[1].split(' ')

['They',
 'were',
 'the',
 'last',
 'people',
 "you'd",
 'expect',
 'to',
 'be',
 'involved',
 'in',
 'anything',
 'strange',
 'or',
 'mysterious,',
 'because',
 'they',
 'just',
 "didn't",
 'hold',
 'with',
 'such',
 'nonsense']

In [13]:
lower_case_list = []  #change words to lowercase
sliced_sentence = sliced_text[1].split(' ')
for word in sliced_sentence:
  lower_case_list.append(word.lower())

In [8]:
#lower_case_list = [word.lower() for word in sliced_sentence]     is also same as the code above

In [14]:
lower_case_list

['they',
 'were',
 'the',
 'last',
 'people',
 "you'd",
 'expect',
 'to',
 'be',
 'involved',
 'in',
 'anything',
 'strange',
 'or',
 'mysterious,',
 'because',
 'they',
 'just',
 "didn't",
 'hold',
 'with',
 'such',
 'nonsense']

In [20]:
def make_corpus(sample_text):
  sentence_level_slice = sample_text.replace('\n', '. ').split('. ')
  sentence_level_slice = [sentence for sentence in sentence_level_slice if sentence != '']  #?? meaning

  word_level_slice = []
  for sentence in sentence_level_slice:
    sentence_in_word = []
    for word in sentence.split(' '):
      sentence_in_word.append(word.lower()) #word turns to lowercase and save to sentence_in_word
    word_level_slice.append(sentence_in_word) #?? why creating word_level_slice when sentence_level_slice is there to use
    print(sentence_in_word)
    print(word_level_slice)
  return word_level_slice
corpus = make_corpus(sample_text)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



----------------------
[['harry', 'potter', 'and', 'the', "sorcerer's", 'stone', '', '', 'chapter', 'one', '', 'the', 'boy', 'who', 'lived', '', 'mr', 'and', 'mrs', 'dursley,', 'of', 'number', 'four,', 'privet', 'drive,', 'were', 'proud', 'to', 'say', 'that', 'they', 'were', 'perfectly', 'normal,', 'thank', 'you', 'very', 'much'], ['they', 'were', 'the', 'last', 'people', "you'd", 'expect', 'to', 'be', 'involved', 'in', 'anything', 'strange', 'or', 'mysterious,', 'because', 'they', 'just', "didn't", 'hold', 'with', 'such', 'nonsense'], ['', 'mr', 'dursley', 'was', 'the', 'director', 'of', 'a', 'firm', 'called', 'grunnings,', 'which', 'made', 'drills'], ['he', 'was', 'a', 'big,', 'beefy', 'man', 'with', 'hardly', 'any', 'neck,', 'although', 'he', 'did', 'have', 'a', 'very', 'large', 'mustache'], ['mrs', 'dursley', 'was', 'thin', 'and', 'blonde', 'and', 'had', 'nearly', 'twice', 'the', 'usual', 'amount', 'of', 'neck,', 'which', 'came', 'in', 'very', 'useful', 'as', 'she', 'spent', 'so', 

In [11]:
corpus[0]

['harry',
 'potter',
 'and',
 'the',
 "sorcerer's",
 'stone',
 '',
 '',
 'chapter',
 'one',
 '',
 'the',
 'boy',
 'who',
 'lived',
 '',
 'mr',
 'and',
 'mrs',
 'dursley,',
 'of',
 'number',
 'four,',
 'privet',
 'drive,',
 'were',
 'proud',
 'to',
 'say',
 'that',
 'they',
 'were',
 'perfectly',
 'normal,',
 'thank',
 'you',
 'very',
 'much']

In [22]:
for every_sentence in corpus:
  for every_word in every_sentence:
    for every_context_word in every_word:
      list(range(-3, 3+1)) #if the window is 3, context word should be in between -3 and 3+1, and 3+1 because 0 is the center word

In [25]:
w_size = 3
word_pairs = []
for sentence in corpus:
  for i, word in enumerate(sentence):   #same as        for i in range(len(sentence)):
                         #               word = sentence[i]
    print(i, word)
    for j in range( max(i-w_size,0), min(i+w_size+1, len(sentence))): #max(a,b)에서는 a,b 둘 중 큰것을 반환한다. 그러므로 여기에선 0이하의 값을 못반환하게 한다.min(a,b)도 같은데 둘 중 작은 것을 반환하며 여기서는 len(sentence)보다 큰 값을 반환 못하게 한다.
      if j == i: #0<range<len(sentence)의 j가 sentence 안의 word index i에 해당되면 그것은 center word이니 다른 range에서 context word을 고르러 for loop으로 간다.
        continue
      context_word = sentence[j] #그 j!=i는 이 코드를 실행하며 i는 center word이고 j는 context word가 된다.
      print(word, context_word, j)
      word_pairs.append((word, context_word))
    # some how get context word for given word


流式输出内容被截断，只能显示最后 5000 行内容。
written books 44
written about 46
written harry 47
written -- 48
46 about
about be 43
about books 44
about written 45
about harry 47
about -- 48
about every 49
47 harry
harry books 44
harry written 45
harry about 46
harry -- 48
harry every 49
harry child 50
48 --
-- written 45
-- about 46
-- harry 47
-- every 49
-- child 50
-- in 51
49 every
every about 46
every harry 47
every -- 48
every child 50
every in 51
every our 52
50 child
child harry 47
child -- 48
child every 49
child in 51
child our 52
child world 53
51 in
in -- 48
in every 49
in child 50
in our 52
in world 53
in will 54
52 our
our every 49
our child 50
our in 51
our world 53
our will 54
our know 55
53 world
world child 50
world in 51
world our 52
world will 54
world know 55
world his 56
54 will
will in 51
will our 52
will world 53
will know 55
will his 56
will name!" 57
55 know
know our 52
know world 53
know will 54
know his 56
know name!" 57
know  58
56 his
his world 53
his will 54
his know 55
hi

In [26]:
word_pairs #(center word, context word in window 3) #?? why the result some show 6 context word for a center but some show 3 context words for center word

[('harry', 'potter'),
 ('harry', 'and'),
 ('harry', 'the'),
 ('potter', 'harry'),
 ('potter', 'and'),
 ('potter', 'the'),
 ('potter', "sorcerer's"),
 ('and', 'harry'),
 ('and', 'potter'),
 ('and', 'the'),
 ('and', "sorcerer's"),
 ('and', 'stone'),
 ('the', 'harry'),
 ('the', 'potter'),
 ('the', 'and'),
 ('the', "sorcerer's"),
 ('the', 'stone'),
 ('the', ''),
 ("sorcerer's", 'potter'),
 ("sorcerer's", 'and'),
 ("sorcerer's", 'the'),
 ("sorcerer's", 'stone'),
 ("sorcerer's", ''),
 ("sorcerer's", ''),
 ('stone', 'and'),
 ('stone', 'the'),
 ('stone', "sorcerer's"),
 ('stone', ''),
 ('stone', ''),
 ('stone', 'chapter'),
 ('', 'the'),
 ('', "sorcerer's"),
 ('', 'stone'),
 ('', ''),
 ('', 'chapter'),
 ('', 'one'),
 ('', "sorcerer's"),
 ('', 'stone'),
 ('', ''),
 ('', 'chapter'),
 ('', 'one'),
 ('', ''),
 ('chapter', 'stone'),
 ('chapter', ''),
 ('chapter', ''),
 ('chapter', 'one'),
 ('chapter', ''),
 ('chapter', 'the'),
 ('one', ''),
 ('one', ''),
 ('one', 'chapter'),
 ('one', ''),
 ('one', '

In [29]:
vocab = sorted(list(set([word for sentence in corpus for word in sentence]))) #set()을 사용하여 중복된 것을 지우고 list로 저장하여 sorted한다.
num_words = len(vocab)

In [28]:
import torch


In [31]:
torch.randn([5,2]) #random numbers whose elements are normally distributed with mean 0, variance , and standard deviation

tensor([[-1.3173,  1.0717],
        [ 1.8953,  1.1602],
        [ 1.4767,  0.4653],
        [ 0.6533,  0.9372],
        [ 0.0707,  1.4200]])

In [34]:
num_dim = 50

word_u_vector = torch.randn([num_words, num_dim]) #?? randn([num_words, num_dim])의 의미
word_v_vector = torch.randn([num_words, num_dim])

In [33]:
word_u_vector[100] #context word u의 vector

tensor([-0.2844, -0.1963, -1.1429,  0.3372, -0.7374, -1.2050,  0.8748, -1.8257,
        -1.2615,  0.3208, -0.9131, -0.8691, -1.9698, -1.0771, -0.2834,  1.2224,
         0.2342, -0.6536,  1.9526,  0.1754, -0.6730, -1.3799, -0.0975,  0.1258,
         1.0372, -0.7938,  0.2316, -0.7994, -1.3084, -0.1407,  1.0502, -0.4465,
         0.2172, -0.8157,  1.2574, -0.8825,  0.6227,  0.1070, -1.1440, -0.3423,
         1.6044, -0.2570, -0.9057,  0.6297,  0.5055, -0.4595, -0.7196,  0.2765,
        -1.1895,  0.2227])

In [37]:
def word2idx(wrd):
  return idx_of_that_word

# wrd2idx_dict = {}
# for i in range(len(vocab)):
#   wrd = vocab[i] #vocab의 한 element, wrd
#   wrd2idx_dict[wrd] = i  #wrd2idx_dict에서의 i index에 wrd를 저장

wrd2idx_dict = {wrd: i for i, wrd in enumerate(vocab)} #same code as above

In [38]:
wrd2idx_dict['harry']

533

In [41]:
word_v_vector[wrd2idx_dict['harry']] #?? 왜 word_v_vector[533]인지, 533의 의미?왜 randn을 여기서는 안쓰는지?  center word v의 vector

tensor([-7.1260e-01, -5.3101e-01, -2.8493e-01,  7.5354e-01, -4.1155e-01,
        -2.4343e-01,  6.5878e-01,  2.9464e-01,  4.6473e-01, -1.0740e+00,
        -1.8361e+00,  5.7281e-01, -2.3740e-01, -8.3867e-01, -1.0400e-01,
        -5.6508e-01,  1.7789e-03, -7.0396e-01, -6.1698e-01, -2.6203e+00,
        -3.6205e-01, -1.0305e+00,  5.0745e-02, -1.1994e+00, -6.4554e-01,
         9.1352e-01,  4.1870e-02, -7.5114e-01, -4.2915e-01,  1.6362e+00,
         3.6377e-01,  1.0551e+00,  9.7691e-01,  4.7659e-01, -1.0687e+00,
        -6.8270e-01,  1.1686e+00, -1.2297e+00,  1.6300e+00,  5.3852e-01,
        -1.5387e+00,  1.0580e+00,  1.1628e+00,  2.8792e-01,  3.2219e-02,
         9.3279e-01, -8.5330e-01,  1.2191e+00, -5.1812e-01, -6.7116e-01])

In [42]:
word_u_vector.data[100, 0] = 1.5 #?? data[100,0]의 의미

In [ ]:
lr = 0.01

prob_record = []
word_u_vector = torch.randn([num_words, num_dim], requires_grad=True)
word_v_vector = torch.randn([num_words, num_dim], requires_grad=True)

for epoch in range(5):
  for pair in word_pairs:
  # pair = word_pairs[0]

    center_word_id = wrd2idx_dict[pair[0]]
    window_word_id = wrd2idx_dict[pair[1]]
    center_word_id, window_word_id

    center_vector = word_v_vector[center_word_id]
    window_vector = word_u_vector[window_word_id]

    dot_product_value = (center_vector * window_vector).sum()
    matmul_output = torch.matmul(center_vector, word_u_vector.T)

    prob = torch.exp(dot_product_value) / torch.exp(matmul_output).sum()
    negative_log_prob = -torch.log(prob + 1e-7)

    negative_log_prob.backward()

    word_u_vector.data = word_u_vector.data - word_u_vector.grad * lr
    word_v_vector.data -= word_v_vector.grad * lr

    word_v_vector.grad = None
    word_u_vector.grad = None
    prob_record.append(prob.item())
# entire_dot_value_for_every_word = []
# for vector in word_u_vector:
#   dot_product_value = (center_vector * vector).sum()
#   entire_dot_value_for_every_word.append(dot_product_value)


In [ ]:
import matplotlib.pyplot as plt

plt.plot(loss_record)

In [ ]:
word_v_vector.grad

In [ ]:
log_prob

In [ ]:
1/num_words

In [ ]:
torch.exp(matmul_output).sum()

In [ ]:
matmul_output[:5]

In [ ]:
entire_dot_value_for_every_word[:5]

In [ ]:
center_vector.shape

In [ ]:
alist = [4,5,7]
unsqueeze_alist = [alist]

alist, unsqueeze_alist

In [ ]:
center_vector.unsqueeze(0)

In [ ]:
center_vector.unsqueeze(0).shape, word_u_vector.T.shape, 


In [ ]:
entire_dot_value_for_every_word

In [ ]:
|